### ISSUE TITLE
[Frontend][Branch: frontend2/23] - Add method stubs for receiving tips in waiting room

### ISSUE THREAD

**Issue by markfloryan** [asci-uva/asci-main#28]
I want you to learn how to write a method stub on the backend server. This will help you more fully implement the front end everytime we have a new feature.

1. Go to backend/src/asci/server/Server.php: run(). This method has a large switch statement for each server command. Add a new one (at the bottom please) called getTip and have it simply return a hardcoded object (something like [result: "success", tips: ["The tip will go here", "second tip"]. 
2. Hook your frontend to call this dummy backend function, receive the response, and display the actual string that is sent back (yes, it will always be the same so far).
3. Have the get next tip button scroll through the array of tips that was sent back from the server.

**Comment by lisagjy** [comment]
Done. Right now the get next tip button is pulling one random tip from the backend (different from the one displayed currently)
