### ISSUE TITLE
Course settings: Create them on the fly if they do not exist.

### ISSUE THREAD

**Issue by markfloryan** [asci-uva/asci-main#77]
If a course does not have an entry in course settings, we currently get an error. Instead, have the backend just create a default set of course settings for the course if there is none already and then proceed to send that back to the frontend.

**Comment by IAMVANN** [comment]
Having trouble recreating the error. Is the error supposed to occur as we create a new course or when we click on the course in Course management and it attempts to load up the assignments?

**Comment by markfloryan** [comment]
You can recreate this by doing the following:

- Go to database and delete a row in the CourseSettings table for some course.
- Go back to the system, log in, and select that particular course when heading towards the queue.
- The error page will appear because the course you selected does not have an entry in the CourseSettings page. It should get created automatically with default settings instead of sending back an error.

**Comment by markfloryan** [comment]
@IAMVANN Is this issue resolved? If so, in which branch? I don't see it in the development branch. If so, please close the issue.
